apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-config
data:
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
  TIMEZONE: {{ .Values.config.TIMEZONE | quote }}
  S3_ENDPOINT: {{ .Values.config.S3_ENDPOINT | quote }}
  BUCKETNAME: {{ .Values.config.BUCKETNAME | quote }}
  METRICS_PORT: {{ .Values.config.METRICS_PORT | quote }}
