apiVersion: v1
kind: Service
metadata:
  name: {{ include "wallet.fullname" . }}-api
  labels:
    {{- include "wallet.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "wallet.selectorLabels" (dict "Release" .Release "Chart" .Chart "Values" .Values "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.api.metricsPort }}
      targetPort: metrics
      protocol: TCP
