apiVersion: v1
kind: Service
metadata:
  name: wallet-service-ui
  labels:
    app.kubernetes.io/component: ui
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: ui
  ports:
    - name: http
      port: {{ .Values.ui.port }}
      targetPort: http
      protocol: TCP
